### ISSUE TITLE
Minor typo in Lesson 20

### ISSUE THREAD

**Issue by khangquangtran** [matloff/fasteR#16]
In the first sentence of the Lesson 20:
> If our Census data example above, it was stated that education codes 0-9 all corresponded to having no college education at all.

Isn't it supposed to be:
"In our Census data example above, it was stated that education codes 0-9 all corresponded to having no college education at all."?
("In" instead of "If" at the beginning.)

**Comment by matloff** [comment]
Yes, thanks, fixed earlier.
