### ISSUE TITLE
Typos in lessons 29, 35, and 36

### ISSUE THREAD

**Issue by clayford** [matloff/fasteR#23]
### Lesson 29: Simple Text Processing, I

The main R function for **concatening** strings is **paset**().   
should be...   
The main R function for **concatenating** strings is **paste**(). 

**y2** <- y1[y1 != '']   
should be...    
**allWords** <- y1[y1 != '']    

### Lesson 35: Files and Folders/Directories

In **assmebling** a dataset for my regtools package, 
should be...
In **assembling** a dataset for my regtools package, 

### Lesson 36: R 'while' Loops

second bullet of key points, 10000 is orphaned.

I love this tutorial! Thank you so much!

**Comment by matloff** [comment]
Thanks very much for the feedback (the more, the better)! Fixed.
