### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by r2evans** [matloff/fasteR#4]
> Uh, oh! 5 women in the study had glucose level 0. And 44 had level 1, etc. Presumably this is not physiologically possible.

The way I'm interpreting it, the numbers are reversed. If you mean that "glucose = 44 had one observation", then my interpretation is wrong.

```
> table(pima$glucose)

  0  44  56  57  61  62  65  67  68  71  72  73  74  75  76  77  78  79  80  81 
  5   1   1   2   1   1   1   1   3   4   1   3   4   2   2   2   4   3   6   6 
...
```

Suggested replacements:

- Uh, oh! 5 women in the study had glucose level 0. And 1 had level 44, etc. Presumably this is not physiologically possible.
- Uh, oh! 5 women in the study had glucose level 0. And one had glucose = 44, etc. Presumably this is not physiologically possible.

And while WebMD says that 60 may be a "normal" pre-meal low ([ref](https://www.webmd.com/diabetes/qa/what-are-normal-blood-sugar-levels)), I don't know the physiological possibility of 44. Since your follow-on fixing code addresses only the five 0s, perhaps  the replacement should instead be:

- Uh, oh! 5 women in the study had glucose level 0. Presumably this is not physiologically possible.

Thanks, nice guide!

**Comment by matloff** [comment]
Thanks, changed. I think I fixed the first part at the time you posted this. Very sorry for the delay.
