### ISSUE TITLE
Some minor typos

### ISSUE THREAD

**Issue by titus483** [matloff/fasteR#5]
In the section:
Another Look at the Nile Data
there is a minor typo:
Just before "Pause to Reflect" begins, there is a sum 1+44=55 - should be 1+54=55.

And in the section Another Look at the Nile Data just below the read.table statement is wrong - should be:
pe <- read.table('https://raw.githubusercontent.com/matloff/fasteR/master/data/prgeng.txt',header=TRUE)

**Comment by matloff** [comment]
Thanks!
